# Generated by Django 2.2.5 on 2019-09-27 10:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('happiness', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='happiness',
            unique_together={('user', 'date')},
        ),
    ]
